language: php

php:
  - 5.5
  - 5.6

sudo: false

install:
  # - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # - composer global require drush/drush:dev-master
  - composer self-update

  # Download Drupal and dependencies.
  - TESTDIR=$(pwd)
  - cd ..
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git drupal
  - git clone --branch 8.x-1.x http://git.drupal.org/project/composer_manager.git drupal/modules/composer_manager
  - cd drupal

before_script:
  # rsync the module directory into modules/xero
  - rsync -rtlDPvc --exclude .git/ $TESTDIR modules/

  # Run the composer manager init script to add drupal-update capability.
  - cd modules/composer_manager
  - php scripts/init.php

  # Change back to the root Drupal directory.
  - cd ../..
  - composer drupal-update --verbose --no-interaction

  # Go back to repository directory to run phpunit.
  - cd modules/xero
script:
  - ../../vendor/bin/phpunit --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt
after_script:
  # Print out coverage report.
  - head $TRAVIS_BUILD_DIR/coverage.txt
