language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  - fast_finish: true

before_install:
  - sudo apt-get update > /dev/null

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

before_script:
  - cd ../..

  # Download Drupal
  - drush pm-download --drupal-project-name=drupal -y drupal-8.0.x
  - cd drupal

  # Download Composer Manager
  - drush pm-download -y composer_manager-8.x-1.x

  # Symlink the repository dir into modules/xero
  - ln -sv $TRAVIS_BUILD_DIR modules/xero

  # Run the composer manager init script to add drupal-update capability.
  - ./modules/composer_manager/scripts/init.sh

  # Change into core directory and run composer drupal-update for dependencies.
  - cd core
  - composer drupal-update

  # Go back to repository directory to run phpunit.
  - cd ../modules/xero
