language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update > /dev/null

install:
  # - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # - composer global require drush/drush:dev-master
  - composer self-update

  # Download Drupal and dependencies.
  - TESTDIR=$(pwd)
  - cd ..
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git drupal
  - git clone --branch 8.x-1.x --depth 1 http://git.drupal.org/project/composer_manager.git drupal/modules/composer_manager
  - cd drupal
  - chmod +x modules/composer_manager/scripts/init.sh

before_script:
  # rsync the module directory into modules/xero
  - rsync -rtlDPvc --exclude .git/ $TESTDIR modules/

  # Run the composer manager init script to add drupal-update capability.
  - ./modules/composer_manager/scripts/init.sh

  # Change into core directory and run composer drupal-update for dependencies.
  - cd core
  - composer -vv drupal-update

  # Go back to repository directory to run phpunit.
  - cd ../modules/xero
script:
  - ../../core/vendor/bin/phpunit --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt
