id: xero_default_settings
label: Xero default configuration
migration_tags:
  - Drupal 6
  - Drupal 7
source:
  plugin: variable
  variables:
    - xero_default_account
plugin:
  'default': xero_default_account
destination:
  plugin: config
  config_name: xero.defaults