id: xero_settings
label: Xero configuration
migration_tags:
  - Drupal 6
  - Drupal 7
source:
  plugin: variable
  variables:
    - xero_consumer_key
    - xero_consumer_secret
    - xero_key_path
process:
  'consumer_key': xero_consumer_key
  'consumer_secret': xero_consumer_secret
  'key_path': xero_key_path
destination:
  plugin: config
  config_name: xero.oauth